# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

init_sparse_matrix <- function(nrow, ncol) {
    .Call('_EigenSmallCountRounding_init_sparse_matrix', PACKAGE = 'EigenSmallCountRounding', nrow, ncol)
}

create_dummy_cpp <- function(groupings_inner, groupings_publish) {
    .Call('_EigenSmallCountRounding_create_dummy_cpp', PACKAGE = 'EigenSmallCountRounding', groupings_inner, groupings_publish)
}

non_zeros_sparse_matrix <- function(mat_xptr) {
    .Call('_EigenSmallCountRounding_non_zeros_sparse_matrix', PACKAGE = 'EigenSmallCountRounding', mat_xptr)
}

print_sparse_matrix <- function(mat_xptr) {
    invisible(.Call('_EigenSmallCountRounding_print_sparse_matrix', PACKAGE = 'EigenSmallCountRounding', mat_xptr))
}

calc_z <- function(mat_xptr, y_i) {
    .Call('_EigenSmallCountRounding_calc_z', PACKAGE = 'EigenSmallCountRounding', mat_xptr, y_i)
}

calc_M <- function(xptr_X, b) {
    .Call('_EigenSmallCountRounding_calc_M', PACKAGE = 'EigenSmallCountRounding', xptr_X, b)
}

calc_c <- function(mat_xptr, z_i) {
    .Call('_EigenSmallCountRounding_calc_c', PACKAGE = 'EigenSmallCountRounding', mat_xptr, z_i)
}

reduce_X_y_cpp <- function(Xptr, y_i, b, z) {
    .Call('_EigenSmallCountRounding_reduce_X_y_cpp', PACKAGE = 'EigenSmallCountRounding', Xptr, y_i, b, z)
}

round_cells_cpp <- function(Xptr, y, b, n_b, max_iter, z_e, seed, z_ = NULL, y0_ = NULL, M_ = NULL) {
    .Call('_EigenSmallCountRounding_round_cells_cpp', PACKAGE = 'EigenSmallCountRounding', Xptr, y, b, n_b, max_iter, z_e, seed, z_, y0_, M_)
}

