# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

init_sparse_matrix <- function(nrow, ncol) {
    .Call('_EigenSmallCountRounding_init_sparse_matrix', PACKAGE = 'EigenSmallCountRounding', nrow, ncol)
}

create_dummy_cpp <- function(groupings_inner, groupings_publish) {
    .Call('_EigenSmallCountRounding_create_dummy_cpp', PACKAGE = 'EigenSmallCountRounding', groupings_inner, groupings_publish)
}

non_zeros_sparse_matrix <- function(mat_xptr) {
    .Call('_EigenSmallCountRounding_non_zeros_sparse_matrix', PACKAGE = 'EigenSmallCountRounding', mat_xptr)
}

print_sparse_matrix <- function(M) {
    invisible(.Call('_EigenSmallCountRounding_print_sparse_matrix', PACKAGE = 'EigenSmallCountRounding', M))
}

